spring.datasource.url=jdbc:mysql://localhost:3306/servigo
spring.datasource.username=root
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=servigo_secret_key_123456789_servigo_seguridad_backend
jwt.expiration=86400000

admin.email=admin@servigo.cl
admin.password=AdminServiGo2026*