spring.datasource.url=jdbc:mysql://yamabiko.proxy.rlwy.net:21525/railway?allowPublicKeyRetrieval=true&useSSL=false

spring.datasource.username=root
spring.datasource.password=GaiVehREpQAWGjbIfZzqPRrNbmOCgPEp
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

cloudinary.cloud-name=dpqjxpxqb
cloudinary.api-key=986484435166457
cloudinary.api-secret=Z5AX6dUdR4QMptCYkDOcQrYc8D0


jwt.secret=servigo_secret_key_123456789_servigo_seguridad_backend
jwt.expiration=86400000

admin.email=admin@servigo.cl
admin.password=AdminServiGo2026*

# SMTP Gmail (contraseña = App Password de 16 caracteres SIN espacios)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=contacto.servigo@gmail.com
spring.mail.password=jhztuitbmrstwfxz
spring.mail.from=contacto.servigo@gmail.com
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000